const data=[
  {
    "id": 1,
    "description":"Centralized management of institutional data enables distinct users to manage their respective activities through a single platform.",
    "company": "Centralized Database",
    "logo": "./images/database.png",
    "new": true,
    "featured": true,
    "position": "Senior Frontend Developer",
    "role": "Frontend",
    "level": "Senior",
    "postedAt": "1d ago",
    "contract": "Full Time",
    "location": "USA Only",
    "languages": ["HTML", "CSS", "JavaScript"],
    "tools": []
  },
  {
    "id": 2,
    "description":"Onsite & Online Support to all users, with roadmaps for implementation enable fastest implementation & active participation of all users.",
    "company": "Absolute Support",
    "logo": "./images/absolutelogo.png",
    "new": true,
    "featured": true,
    "position": "Fullstack Developer",
    "role": "Fullstack",
    "level": "Midweight",
    "postedAt": "1d ago",
    "contract": "Part Time",
    "location": "Remote",
    "languages": ["Python"],
    "tools": ["React"]
  },
  {
    "id": 3,
    "description":"Secure cloud, role-based access, password & OTP encryption, auto-alerts for data security, located in earthquake-free zones & multiple back-ups ensuring disaster recovery.",
    "company": "Data Security",
    "logo": "./images/datasec.jpg",
    "new": true,
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2d ago",
    "contract": "Part Time",
    "location": "USA Only",
    "languages": ["JavaScript"],
    "tools": ["React", "Sass"]
  },
  {
    "id": 4,
    "description":"Easy & intuitive structure supporting vernacular languages & tool tips for helping users to adopt easily & navigate with ease.",
    "company": "Easy and inutative solutions",
    "logo": "./images/kk.jpg",
    "new": false,
    "featured": false,
    "position": "Junior Frontend Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "5d ago",
    "contract": "Contract",
    "location": "USA Only",
    "languages": ["CSS", "JavaScript"],
    "tools": []
  },
  {
    "id": 5,
    "description":"Analytics powered dashboards for accessing actionable real-time information & generating reports for better decision-making & compliance.",
    "company": "Dashboard & Reports",
    "logo": "./images/dashboard.png",
    "new": false,
    "featured": false,
    "position": "Software Engineer",
    "role": "FullStack",
    "level": "Midweight",
    "postedAt": "1w ago",
    "contract": "Full Time",
    "location": "Worldwide",
    "languages": ["JavaScript"],
    "tools": ["Ruby", "Sass"]
  },
  {
    "id": 6,
    "description":"Some brief description about the company to help the candidate to research about it.",
    "company": "Online exams and interviews",
    "logo": "./images/ot.jpg",
    "new": false,
    "featured": false,
    "position": "Junior Backend Developer",
    "role": "Backend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "UK Only",
    "languages": ["Ruby"],
    "tools": ["RoR"]
  },
  {
    "id": 7,
    "description":"Some brief description about the company to help the candidate to research about it.",
    "company": "Chat-bot support",
    "logo": "./images/chatbot.png",
    "new": false,
    "featured": false,
    "position": "Junior Developer",
    "role": "Frontend",
    "level": "Junior",
    "postedAt": "2w ago",
    "contract": "Full Time",
    "location": "Worldwide",
    "languages": ["HTML", "JavaScript"],
    "tools": ["Sass"]
  },
  // {
  //   "id": 8,
  //   "description":"Some brief description about the company to help the candidate to research about it.",
  //   "company": "Insure",
  //   "logo": "./images/insure.svg",
  //   "new": false,
  //   "featured": false,
  //   "position": "Junior Frontend Developer",
  //   "role": "Frontend",
  //   "level": "Junior",
  //   "postedAt": "2w ago",
  //   "contract": "Full Time",
  //   "location": "USA Only",
  //   "languages": ["JavaScript"],
  //   "tools": ["Vue", "Sass"]
  // },
  // {
  //   "id": 9,
  //   "description":"Some brief description about the company to help the candidate to research about it.",
  //   "company": "Eyecam Co.",
  //   "logo": "./images/eyecam-co.svg",
  //   "new": false,
  //   "featured": false,
  //   "position": "Full Stack Engineer",
  //   "role": "Fullstack",
  //   "level": "Midweight",
  //   "postedAt": "3w ago",
  //   "contract": "Full Time",
  //   "location": "Worldwide",
  //   "languages": ["JavaScript", "Python"],
  //   "tools": ["Django"]
  // },
  // {
  //   "id": 10,
  //   "description":"Some brief description about the company to help the candidate to research about it.",
  //   "company": "The Air Filter Company",
  //   "logo": "./images/the-air-filter-company.svg",
  //   "new": false,
  //   "featured": false,
  //   "position": "Front-end Dev",
  //   "role": "Frontend",
  //   "level": "Junior",
  //   "postedAt": "1mo ago",
  //   "contract": "Part Time",
  //   "location": "Worldwide",
  //   "languages": ["JavaScript"],
  //   "tools": ["React", "Sass"]
  // }
]


export default data;