import React from 'react'
import { useNavigate } from 'react-router-dom';
import classes from "./Modal.module.css"

function Modal(props) {
  const navigate = useNavigate();

  if(!props.modal){
    return null;
  }  
  return (
    <div className={classes.overlay} onClick={props.closemodal}>
    <div className={classes.message}>
    <div className={classes.heading}>Instructions</div>
    <ul>
      <li>Ensure that your Webcam and mic are functioning properly</li>
      <li>The Server provides a new autogenerated id to a client after each refresh.</li>
      <li>Copy the ID provided to you from the Editor and text it to the Admin by the Chat app through a new Tab</li>
      <li>You will recieve the Call at the alloted time from the Admin</li>
    </ul>
    <div className={classes.actions}>
    <button onClick={() => {window.open("/interview", "_blank");}} className={classes.button1}>PROCEED</button>
    <button onClick={props.closemodal} className={classes.button2}>CLOSE</button>
    </div>
   </div>
   </div>
  )
}

export default Modal;